---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: secret-store.vsphere.vmware.com
spec:
  displayName: "Secret Store Service"
  iconSVGBase64: ""
  longDescription: "VMware Cloud Foundation Secret Store Supervisor Service"
  shortDescription: "Secret Store Supervisor Service for VCF"
  providerName: Broadcom
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: secret-store.vsphere.vmware.com.9.1.0+25367485
spec:
  refName: secret-store.vsphere.vmware.com
  version: 9.1.0+25367485
  releasedAt: 2026-04-17T12:20:37Z
  valuesSchema:
    openAPIv3:
      title: secret-store.vsphere.vmware.com values schema
      required:
        - virtualIP
      properties:
        virtualIP:
          type: string
          description: Autowired property, do not enter value - Control plane address. This is the IP or hostname that external components will use to communicate with the secret store's control plane.
        statefulSet:
          type: object
          description: Configuration settings specific to the Kubernetes StatefulSet deployment of the secret store.
          properties:
            storageClassName:
              type: string
              description: Name of the storage class to be used for persistent volumes required by the StatefulSet.
            required:
              - storageClassName
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.packages.broadcom.com/vsphere/iaas/secret-store-service/9.1.0.0/secret-store-service/9.1.0.0.25367485:9.1.0.0.25367485
      template:
        - ytt:
            paths:
              - config
        - kbld:
            paths:
              - '-'
              - .imgpkg/images.yml
      deploy:
        - kapp:
            rawOptions:
              - --wait-timeout=5m
              - --kube-api-qps=20
              - --kube-api-burst=30

